apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cache-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- if and (eq .Values.cache.type "redis") (.Values.cache.create) }}
  hostname: {{ .Release.Name }}-redis
  {{- else }}
  hostname: {{ .Values.cache.hostname }}
  {{- end }}
  port: {{ .Values.cache.port | quote }}
