{{- if and (eq .Values.database.type "postgres") (.Values.database.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: postgres-controller
data:
  db-host: {{ .Values.database.host }}
  db-name: {{ .Values.database.name }}
  db-user: {{ .Values.database.user }}
  {{- if .Values.database.port }}
  db-port: {{ .Values.database.port | quote }}
  {{- else }}
  db-port: "5432"
  {{- end }}
{{- end -}}
