{{- if and (eq .Values.database.type "postgres") (.Values.database.create) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-password
  namespace: postgres-controller
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
{{- end -}}
